name: books
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^7.1.2
  curved_navigation_bar: ^1.0.3
  google_maps_flutter: ^2.5.0
  http: ^1.2.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/font/OpenSans-VariableFont_wdth,wght.ttf
