name: books
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.1.1


  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts: # <-- This 'fonts:' line MUST NOT be commented out and must be indented exactly two spaces under 'flutter:'
    - family: Open Sans # This 'family:' line must be indented exactly four spaces under 'flutter:'
      fonts: # <-- This 'fonts:' line must be indented exactly six spaces under 'flutter:'
        - asset: assets/font/OpenSans-VariableFont_wdth,wght.ttf # <-- This 'asset:' line must be indented exactly eight spaces under 'flutter:'
          # If you have other weights/styles, add them here with correct indentation
          # For example:
          # - asset: assets/font/OpenSans-Regular.ttf
          # - asset: assets/font/OpenSans-Bold.ttf
          #   weight: 700